#!/bin/bash

DOCKER='/usr/bin/docker'
FMT_IP='{{ .NetworkSettings.IPAddress }}'
FMT_NETWORK='{{range .NetworkSettings.Networks}}{{.IPAddress}},{{end}}'
FMT_HEALTH='{{ .State.Health.Status }}'
FMT_RUNNING='{{ .State.Running }}'
FMT_STARTED='{{ .State.StartedAt }}'
INSPECT="$DOCKER inspect"

CONTAINER="$1"

$DOCKER ps > /dev/null 2>&1
returncode=$?
if [ $returncode -eq 1 ]; then
  echo "CRITICAL: Docker engine not running."
  exit 2
elif [ $returncode -ne 0 ]; then
  echo "UNKNOWN: Docker is in unknow state."
  exit 3
fi

if [[ -z "$CONTAINER" ]]; then
  echo -n "OK: Docker engine running | Containers=$($DOCKER ps -q | wc -l) "
  echo "Images=$($DOCKER images -q | wc -l)"
  exit 0
fi

CONTAINER_U=$(echo $CONTAINER | tr [:lower:] [:upper:])
RUNNING=$($INSPECT --format="${FMT_RUNNING}" $CONTAINER 2> /dev/null)
if [ $? -eq 1 ]; then
  echo "$CONTAINER_U CRITICAL: Container does not exist."
  exit 2
fi
if [ "$RUNNING" == "false" ]; then
  echo "$CONTAINER_U WARNING: Container is not running."
  exit 1
fi
HEALTH=$($INSPECT --format="${FMT_HEALTH}" $CONTAINER 2> /dev/null)
if [ -z "$HEALTH" ]; then
  HEALTH="healthchecks are not implemented"
elif [ "$HEALTH" != "healthy" ]; then
  echo "$CONTAINER_U WARNING: Container is $HEALTH."
  exit 1
fi
STARTED=$(date --date="$($INSPECT --format="${FMT_STARTED}" $CONTAINER)")
if [ -z "$STARTED" ]; then
  STARTED=${RAW_STARTED:-"Unknown"}
  started_epoch=0
else
  started_epoch=$(date --date="$STARTED" +%s)
fi
now=$(date +%s)
if [[ "$started_epoch" -gt $((now-60)) ]]; then
  echo "$CONTAINER_U WARNING: Container just restarted at $(date \
                                                            --date="$STARTED")"
  exit 1
fi
NETWORK=$($INSPECT --format="${FMT_IP}" $CONTAINER)
if [ -z "$NETWORK" ]; then
  NETWORK=$($INSPECT --format="$FMT_NETWORK" $CONTAINER | sed 's/,$//')
fi
echo -n "$CONTAINER_U OK: Container is running and $HEALTH"
echo " | IP: $NETWORK, StartedAt: $STARTED"
exit 0
